### ISSUE TITLE
Add logo to Page

### ISSUE THREAD

**Issue by ikurotime** [ikurotime/GeoWeather#1]
Submit a logo for the banner, if it match the page, it will be added!

**Comment by KaranSinghBisht** [comment]
Hey @ikurotime, any specifications for the logo?

**Comment by ikurotime** [comment]
Hey @KaranSinghBisht ! Something minimalistic that fits with the page right now is fine 👍

**Comment by KaranSinghBisht** [comment]
Hey @ikurotime, here are a few ideas i came up with 
![Asset 5](https://user-images.githubusercontent.com/69008866/193432104-d73e9124-6d74-451c-a2ec-ed5f580e76ee.png)
![Asset 6](https://user-images.githubusercontent.com/69008866/193432105-6d6f6d04-9438-48aa-bd11-c73b0ad27af1.png)
![Asset 2](https://user-images.githubusercontent.com/69008866/193432106-3d1862a7-0950-491f-b9da-8572622b79fc.png)
![Asset 3](https://user-images.githubusercontent.com/69008866/193432107-e9111459-05ca-435e-aa82-d24734af3959.png)
![Asset 4](https://user-images.githubusercontent.com/69008866/193432108-eab79570-259f-4dc3-97f4-1fecfa13e414.png)

**Comment by ikurotime** [comment]
That's awesome! Both 3 and 4 would look nice with the page 🙌

**Comment by KaranSinghBisht** [comment]
Thanks alot! What dimensions should the banner be in? Also, should I add both 3 and 4 and then pr?

**Comment by ikurotime** [comment]
@KaranSinghBisht 
I think this would be great for the navbar, you can add both to the img folder https://github.com/ikurotime/GeoWeather/tree/master/src/img
I don't mind the size, as long it doesn't modify the current size of the navbar.
<img width="346" alt="Screenshot 2022-10-02 at 01 57 35" src="https://user-images.githubusercontent.com/77805983/193432370-5ab10e4e-e63b-444b-80a4-da412d4fb7f7.png">

**Comment by KaranSinghBisht** [comment]
I am adding the logo as png as well as SVG, and hence you would be able to edit the size using CSS, so there will be no issue with the navbar. Hope it helps 😀!
