### ISSUE TITLE
Add themes to page

### ISSUE THREAD

**Issue by ikurotime** [ikurotime/GeoWeather#3]
Do you feel brave? try adding a theme mechanic to the page. It would be interesting!

**Comment by ighmaZ** [comment]
would love to work on this

**Comment by ikurotime** [comment]
Hey @ighmaZ ! Sure! Give it a try

**Comment by ighmaZ** [comment]
@ikurotime what needs to be done here ?

**Comment by ikurotime** [comment]
@ighmaZ I opened this issue without giving too much thought, anything that could improve the page would be great, a whole theme feature might me too much, contribute in the best way you can and I'll add that, if you don't feel like it, just let me know and I will re assign the issue

**Comment by ighmaZ** [comment]
ill do that thanks
